// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZX0cQv3KV_HVboa7SWufRPpcLMyAhn8',
    appId: '1:337668274409:web:b5586672eb942996619878',
    messagingSenderId: '337668274409',
    projectId: 'flutterauthtemplate-8a7a8',
    authDomain: 'flutterauthtemplate-8a7a8.firebaseapp.com',
    storageBucket: 'flutterauthtemplate-8a7a8.appspot.com',
    measurementId: 'G-3760EYFS9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTeXCBdPCnl1VweBVVqRHCRk7qA9evpQ',
    appId: '1:337668274409:android:fafab2e66b96f87d619878',
    messagingSenderId: '337668274409',
    projectId: 'flutterauthtemplate-8a7a8',
    storageBucket: 'flutterauthtemplate-8a7a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBdvufstwt96uT29SpLPPU5WV7I3BTtCQ',
    appId: '1:337668274409:ios:3cd9604bd61e9d64619878',
    messagingSenderId: '337668274409',
    projectId: 'flutterauthtemplate-8a7a8',
    storageBucket: 'flutterauthtemplate-8a7a8.appspot.com',
    iosBundleId: 'com.example.authTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBdvufstwt96uT29SpLPPU5WV7I3BTtCQ',
    appId: '1:337668274409:ios:3cd9604bd61e9d64619878',
    messagingSenderId: '337668274409',
    projectId: 'flutterauthtemplate-8a7a8',
    storageBucket: 'flutterauthtemplate-8a7a8.appspot.com',
    iosBundleId: 'com.example.authTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ZX0cQv3KV_HVboa7SWufRPpcLMyAhn8',
    appId: '1:337668274409:web:d764d7824bf57e21619878',
    messagingSenderId: '337668274409',
    projectId: 'flutterauthtemplate-8a7a8',
    authDomain: 'flutterauthtemplate-8a7a8.firebaseapp.com',
    storageBucket: 'flutterauthtemplate-8a7a8.appspot.com',
    measurementId: 'G-DXDY8EZ690',
  );
}
